### ISSUE TITLE
Want to Generate Instruction Dataset using OpenSource LLM

### ISSUE THREAD

**Issue by AbrahimZaman360** [stochasticai/xTuring#234]
There is just ChatGPT Option for Generating Dataset.
I want to use my open-source model, how to do so?

**Comment by tushar2407** [comment]
Hi @AbrahimZaman360, 
In order to do so, you can modify [this](https://github.com/stochasticai/xTuring/blob/main/src/xturing/model_apis/openai.py) file and/or make contribution to include new class for Azure. 
For contribution guide, head [here](https://xturing.stochastic.ai/contributing/general_rules).
