### ISSUE TITLE
How to use personal data?

### ISSUE THREAD

**Issue by lhallee** [stochasticai/xturing#82]
Hello,

How would I set up a corpus of text data to be compatible with your trainers from scratch?

**Comment by jamescheong** [comment]
Hi,

Just wonder if it is possible to offer a function to convert instruct in txt to .arrow?

Thanks a lot for your consideration.

Cheers

**Comment by Toan-Do** [comment]
Hi @lhallee,

In order to use xTuring, you need to convert your dataset to our format. Check out our document about the required dataset format : https://xturing.stochastic.ai/datasets/usage

If you want to perform unsupervised fine-tune on the large corpus. You should use TextDataset, split your corpus to many smaller chunk texts, put these chunk texts to the target column and leave the input column as empty.
